using System;
using System.Collections.Generic;

namespace Peak.AP
{
    /// <summary>
    /// Centralized mapping of item internal names to their database IDs.
    /// </summary>
    public static class ItemIdMappings
    {
        /// <summary>
        /// Maps internal item names (as used in ItemDatabase) to their item IDs.
        /// </summary>
        public static readonly Dictionary<string, ushort> NameToId = new(StringComparer.OrdinalIgnoreCase)
        {
            { "Airplane Food", 0 },
            { "Anti-Rope Spool", 1 },
            { "Antidote", 2 },
            { "Apple Berry Green", 3 },
            { "Apple Berry Red", 4 },
            { "Apple Berry Yellow", 5 },
            { "Backpack", 6 },
            { "Bandages", 7 },
            { "Beehive", 8 },
            { "Berrynana Blue", 9 },
            { "Berrynana Brown", 10 },
            { "Berrynana Pink", 11 },
            { "Berrynana Yellow", 12 },
            { "BingBong", 13 },
            { "Binoculars", 14 },
            { "Bugle", 15 },
            { "Bugle_Magic", 16 },
            { "ChainShooter", 17 },
            { "ClimbingSpike", 18 },
            { "Clusterberry Black", 19 },
            { "Clusterberry Red", 20 },
            { "Clusterberry Yellow", 21 },
            { "Clusterberry_UNUSED", 22 },
            { "Compass", 23 },
            { "Cure-All", 24 },
            { "Cursed Skull", 25 },
            { "Egg", 26 },
            { "Energy Drink", 27 },
            { "FireWood", 28 },
            { "FirstAidKit", 29 },
            { "Flag_Plantable_Checkpoint", 30 },
            { "Flare", 32 },
            { "Granola Bar", 33 },
            { "Guidebook", 34 },
            { "Heat Pack", 35 },
            { "Item_Coconut", 36 },
            { "BalloonBunch", 37 },
            { "Item_Honeycomb", 38 },
            { "Berrynana Peel Pink Variant", 39 },
            { "Kingberry Purple", 40 },
            { "Kingberry Yellow", 41 },
            { "Lantern", 42 },
            { "Lantern_Faerie", 43 },
            { "Lollipop", 44 },
            { "MagicBean", 45 },
            { "Marshmallow", 46 },
            { "AncientIdol", 47 },
            { "CactusBall", 48 },
            { "GuidebookPageScroll Variant", 49 },
            { "GuidebookPage_0_Intro", 50 },
            { "Mushroom Glow", 51 },
            { "GuidebookPage_2_Campfire", 52 },
            { "GuidebookPage_3_Revival", 53 },
            { "GuidebookPage_7_Crashout Variant", 54 },
            { "Item_Coconut_half", 55 },
            { "Kingberry Green", 56 },
            { "NestEgg", 57 },
            { "PandorasBox", 58 },
            { "Passport", 59 },
            { "Pepper Berry", 60 },
            { "Pirate Compass", 61 },
            { "PortableStovetopItem", 62 },
            { "RopeShooter", 63 },
            { "RopeShooterAnti", 64 },
            { "RopeSpool", 65 },
            { "ScoutCookies", 66 },
            { "ScoutEffigy", 67 },
            { "ShelfShroom", 68 },
            { "Shell Big", 69 },
            { "HealingDart Variant", 70 },
            { "Sports Drink", 71 },
            { "Stone", 72 },
            { "TrailMix", 73 },
            { "Warp Compass", 74 },
            { "Winterberry Orange", 75 },
            { "Winterberry Yellow", 76 },
            { "Bugle_Scoutmaster Variant", 77 },
            { "Megaphone", 78 },
            { "BounceShroom", 79 },
            { "GuidebookPage", 80 },
            { "MedicinalRoot", 81 },
            { "GuidebookPage_1_Mushrooms", 82 },
            { "Mushroom Chubby", 83 },
            { "Mushroom Cluster Poison", 84 },
            { "GuidebookPage_4_BodyHeat Variant", 85 },
            { "GuidebookPage_5_Sleepy Variant", 86 },
            { "GuidebookPage_6_Awake Variant", 87 },
            { "Mushroom Cluster", 88 },
            { "Mushroom Lace Poison", 89 },
            { "HealingPuffShroom", 90 },
            { "Berrynana Peel Blue Variant", 91 },
            { "Berrynana Peel Brown Variant", 92 },
            { "Mushroom Lace", 93 },
            { "Berrynana Peel Yellow", 94 },
            { "Bugfix", 95 },
            { "GuidebookPage_8_FirstTeams", 96 },
            { "Mushroom Normie Poison", 97 },
            { "Parasol", 98 },
            { "Frisbee", 99 },
            { "RescueHook", 100 },
            { "AloeVera", 101 },
            { "Mushroom Normie", 102 },
            { "Prickleberry_Gold", 103 },
            { "Sunscreen", 104 },
            { "Balloon", 105 },
            { "Dynamite", 106 },
            { "ScoutCannonItem", 107 },
            { "Prickleberry_Red", 108 },
            { "Torch", 109 },
            { "Napberry", 110 },
            { "Scorpion", 111 },
            { "Strange Gem", 112 },
            { "Cheat Compass", 113 },
            { "EggTurkey", 114 },
            { "BookOfBones", 115 },
            { "ClimbingChalk", 116 },
            { "CloudFungus", 117 },
            { "C_Bishop_f Variant", 118 },
            { "C_Bishop_f", 119 },
            { "C_Bishop_m Variant", 120 },
            { "C_Bishop_m", 121 },
            { "C_King Variant", 122 },
            { "C_King", 123 },
            { "BingBong_Prop Variant", 124 },
            { "Binoculars_Prop", 125 },
            { "Bugle_Prop Variant", 126 },
            { "C_Bishop B", 127 },
            { "C_Bishop W", 128 },
            { "C_King B", 129 },
            { "C_King W", 130 },
            { "C_Knight B", 131 },
            { "C_Knight W", 132 },
            { "C_Pawn B", 133 },
            { "C_Pawn W", 134 },
            { "C_Queen B", 135 },
            { "C_Queen W", 136 },
            { "C_Rook B", 137 },
            { "C_Rook W", 138 },
            { "Lollipop_Prop", 139 },
            { "C_Knight Variant", 140 },
            { "C_Knight", 141 },
            { "C_Pawn_f Variant", 142 },
            { "C_Pawn_f", 143 },
            { "C_Pawn_m Variant", 144 },
            { "C_Pawn_m", 145 },
            { "C_Queen Variant", 146 },
            { "C_Queen", 147 },
            { "C_Rook_f Variant", 148 },
            { "C_Rook_f", 149 },
            { "C_Rook_m Variant", 150 },
            { "C_Rook_m", 151 },
            { "FortifiedMilk", 152 },
            { "FortifiedMilk_TEMP", 153 },
            { "Glizzy", 154 },
            { "Mandrake", 155 },
            { "Mandrake_Hidden", 156 },
            { "ScoutCookies_Vanilla", 157 },
            { "Shroomberry_Blue", 158 },
            { "Shroomberry_Green", 159 },
            { "Shroomberry_Purple", 160 },
            { "Shroomberry_Red", 161 },
            { "Shroomberry_Yellow", 162 },
            { "Skull", 163 },
            { "Parasol_Roots Variant", 164 },
        };

        /// <summary>
        /// Maps AP item names to internal game names.
        /// </summary>
        public static readonly Dictionary<string, string> ApNameToInternalName = new(StringComparer.OrdinalIgnoreCase)
        {
            { "Rope Spool", "RopeSpool" },
            { "Rope Cannon", "RopeShooter" },
            { "Anti-Rope Spool", "Anti-Rope Spool" },
            { "Anti-Rope Cannon", "RopeShooterAnti" },
            { "Chain Launcher", "ChainShooter" },
            { "Piton", "ClimbingSpike" },
            { "Rescue Claw", "RescueHook" },
            { "Magic Bean", "MagicBean" },
            { "Parasol", "Parasol" },
            { "Balloon", "Balloon" },
            { "Balloon Bunch", "BalloonBunch" },
            { "Scout Cannon", "ScoutCannonItem" },
            { "Flying Disc", "Frisbee" },
            { "Guidebook", "Guidebook" },
            { "Portable Stove", "PortableStovetopItem" },
            { "Checkpoint Flag", "Flag_Plantable_Checkpoint" },
            { "Lantern", "Lantern" },
            { "Flare", "Flare" },
            { "Torch", "Torch" },
            { "Faerie Lantern", "Lantern_Faerie" },
            { "Blowgun", "HealingDart Variant" },
            { "Cactus", "CactusBall" },
            { "Compass", "Compass" },
            { "Pirate's Compass", "Pirate Compass" },
            { "Binoculars", "Binoculars" },
            { "Bandages", "Bandages" },
            { "First-Aid Kit", "FirstAidKit" },
            { "Antidote", "Antidote" },
            { "Heat Pack", "Heat Pack" },
            { "Cure-All", "Cure-All" },
            { "Remedy Fungus", "HealingPuffShroom" },
            { "Medicinal Root", "MedicinalRoot" },
            { "Aloe Vera", "AloeVera" },
            { "Sunscreen", "Sunscreen" },
            { "Marshmallow", "Marshmallow" },
            { "Glizzy", "Glizzy" },
            { "Fortified Milk", "FortifiedMilk" },
            { "Scout Effigy", "ScoutEffigy" },
            { "Cursed Skull", "Cursed Skull" },
            { "Pandora's Lunchbox", "PandorasBox" },
            { "Ancient Idol", "AncientIdol" },
            { "Strange Gem", "Strange Gem" },
            { "Book of Bones", "BookOfBones" },
            { "Cloud Fungus", "CloudFungus" },
            { "Bugle of Friendship", "Bugle_Magic" },
            { "Bugle", "Bugle" },
            { "Shelf Shroom", "ShelfShroom" },
            { "Bounce Shroom", "BounceShroom" },
            { "Button Shroom", "Mushroom Normie" },
            { "Bugle Shroom", "Mushroom Lace" },
            { "Cluster Shroom", "Mushroom Cluster" },
            { "Chubby Shroom", "Mushroom Chubby" },
            { "Trail Mix", "TrailMix" },
            { "Granola Bar", "Granola Bar" },
            { "Scout Cookies", "ScoutCookies" },
            { "Airline Food", "Airplane Food" },
            { "Energy Drink", "Energy Drink" },
            { "Sports Drink", "Sports Drink" },
            { "Big Lollipop", "Lollipop" },
            { "Big Egg", "NestEgg" },
            { "Egg", "Egg" },
            { "Cooked Bird", "EggTurkey" },
            { "Honeycomb", "Item_Honeycomb" },
            { "Beehive", "Beehive" },
            { "Scorpion", "Scorpion" },
            { "Tick", "Bugfix" },
            { "Conch", "Shell Big" },
            { "Dynamite", "Dynamite" },
            { "Bing Bong", "BingBong" },
            { "Mandrake", "Mandrake" },
            { "Red Crispberry", "Apple Berry Red" },
            { "Green Crispberry", "Apple Berry Green" },
            { "Yellow Crispberry", "Apple Berry Yellow" },
            { "Coconut", "Item_Coconut" },
            { "Coconut Half", "Item_Coconut_half" },
            { "Brown Berrynana", "Berrynana Brown" },
            { "Blue Berrynana", "Berrynana Blue" },
            { "Pink Berrynana", "Berrynana Pink" },
            { "Yellow Berrynana", "Berrynana Yellow" },
            { "Orange Winterberry", "Winterberry Orange" },
            { "Yellow Winterberry", "Winterberry Yellow" },
            { "Red Prickleberry", "Prickleberry_Red" },
            { "Gold Prickleberry", "Prickleberry_Gold" },
            { "Red Shroomberry", "Shroomberry_Red" },
            { "Blue Shroomberry", "Shroomberry_Blue" },
            { "Green Shroomberry", "Shroomberry_Green" },
            { "Yellow Shroomberry", "Shroomberry_Yellow" },
            { "Purple Shroomberry", "Shroomberry_Purple" },
            { "Purple Kingberry", "Kingberry Purple" },
            { "Yellow Kingberry", "Kingberry Yellow" },
            { "Green Kingberry", "Kingberry Green" },
            { "Napberry", "Napberry" },
            { "Black Clusterberry", "Clusterberry Black" },
            { "Red Clusterberry", "Clusterberry Red" },
            { "Yellow Clusterberry", "Clusterberry Yellow" },
            { "Scoutmaster's Bugle", "Bugle_Scoutmaster Variant" },
        };

        /// <summary>
        /// Try to get an item ID by its internal name.
        /// </summary>
        public static bool TryGetId(string itemName, out ushort itemId)
        {
            return NameToId.TryGetValue(itemName, out itemId);
        }

        /// <summary>
        /// Try to get an item ID by its AP item name.
        /// </summary>
        public static bool TryGetIdFromApName(string apItemName, out ushort itemId)
        {
            itemId = 0;
            if (ApNameToInternalName.TryGetValue(apItemName, out string internalName))
            {
                return NameToId.TryGetValue(internalName, out itemId);
            }
            return false;
        }

        /// <summary>
        /// Get all item IDs that are tracked by AP (have an AP name mapping).
        /// </summary>
        public static HashSet<ushort> GetAllApTrackedItemIds()
        {
            var ids = new HashSet<ushort>();
            foreach (var apName in ApNameToInternalName.Keys)
            {
                if (TryGetIdFromApName(apName, out ushort id))
                {
                    ids.Add(id);
                }
            }
            return ids;
        }
    }
}